baseURL = "https://sameer000.github.io/IM/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Airspace for Hugo"
[[menu.footer]]
name = "Services"
url = "#"
weight = 3
[[menu.footer]]
name = "Terms"
url = "#"
weight = 6
[[menu.footer]]
name = "Blog"
url = "blog"
weight = 5
[[menu.footer]]
name = "How it works"
url = "work"
weight = 4
[[menu.footer]]
name = "Contact us"
url = "contact"
weight = 2
[[menu.footer]]
name = "About us"
url = "#"
weight = 1
[[menu.header]]
name = "Work"
url = "work"
weight = 1
[[menu.header]]
name = "Contact"
url = "contact"
weight = 4
[[menu.header]]
name = "Service"
url = "service"
weight = 3
[[menu.header]]
name = "Blog"
url = "blog"
weight = 2
[params]
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
bgImage = "img/call-to-action-bg.jpg"
enable = true
paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
title = "We design delightful digital experiences."
[params.call.button]
text = "tell us your story"
url = "#"
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.feature]
bgImage = "img/feature-bg.jpg"
content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
enable = true
title = "We believe in great ideas"
[params.feature.button]
caption = "View Works"
url = "#"
[params.slider]
bgImage = "img/slider-bg.jpg"
btnText = "Discover Our Projects"
enable = true
subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"
title = "A digital marketing &amp; design agency"
url = "#"
[params.wrapper]
enable = true
image = "img/wrapper-img.png"
italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"
title = "About Us"
